name: Bank Marketing CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python Version
        run: python --version


  validate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check README File
        run: test -f README.md

      - name: Check Project Folders
        run: |
          test -d Notebooks
          test -d Architecture
          test -d Pipeline
          test -d PowerBI

      - name: List Repository Files
        run: ls -la


  test:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Count Notebooks
        run: find Notebooks -name "*.ipynb" | wc -l

      - name: Count Total Files
        run: find . -type f | wc -l


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Project
        run: echo "Project deployed successfully!"
